version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - /tmp/app/redis:/data
    networks:
      - ta_bot_net

  bot_api:
    build: ./API/TA_BOT
    command: >
      sh -c "python3 manage.py migrate &&
            python3 manage.py createsuperuser --noinput &&
            python3 manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./API/TA_BOT/TA_BOT/.env
    volumes:
      - ./db:/app/db/
    depends_on:
      - redis
    networks:
      - ta_bot_net

  bot:
    build: ./TelegramBot
    restart: always
    env_file:
      - ./TelegramBot/.env
    depends_on:
      - bot_api
    networks:
      - ta_bot_net

networks:
  ta_bot_net:
    driver: bridge