version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - /tmp/app/redis:/data
    networks:
      - ta_bot_net

  api:
    build: ./API/TA_BOT
    command: >
      sh -c "python3 -u manage.py migrate &&
            python3 -u manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - API_HOST=api
    volumes:
      - ./db:/app/db/
    depends_on:
      - redis
    networks:
      - ta_bot_net

  bot:
    build: ./TelegramBot
    restart: always
    env_file:
      - ./.env
    environment:
      - API_HOST=api
    depends_on:
      - api
    networks:
      - ta_bot_net

networks:
  ta_bot_net:
    driver: bridge