# Generated by Django 3.2.7 on 2021-10-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0002_auto_20210928_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramactivesessions',
            name='allow_notif',
            field=models.BooleanField(default=False),
        ),
    ]
