# Generated by Django 3.2.7 on 2021-10-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0005_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(max_length=1024),
        ),
    ]
