# Generated by Django 3.2.7 on 2021-10-08 01:00

import TA_BOT_API.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0006_alter_resource_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1024)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('file', models.FileField(null=True, upload_to=TA_BOT_API.models.homework_file_directory_path)),
                ('due_date', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('grade', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_BOT_API.grade')),
            ],
        ),
    ]
