# Generated by Django 3.2.7 on 2021-10-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0007_grade_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='due_date',
            new_name='due_date_time',
        ),
    ]
