# Generated by Django 3.2.7 on 2021-10-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0008_rename_due_date_homework_due_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due_date_time',
            field=models.DateTimeField(),
        ),
    ]
