# Generated by Django 3.2.7 on 2021-10-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0011_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='source_chat_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
