# Generated by Django 3.2.7 on 2021-10-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0013_auto_20211031_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='file_id',
            field=models.CharField(max_length=128),
        ),
    ]
