# Generated by Django 3.2.7 on 2021-10-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0014_alter_homework_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='file_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
