# Generated by Django 3.2.7 on 2021-12-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0015_alter_homework_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authdata',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='authdata',
            name='password',
            field=models.CharField(default='password', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
