# Generated by Django 3.2.7 on 2021-12-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0016_auto_20211229_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='authdata',
            name='student_id',
            field=models.CharField(default=9831034, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authdata',
            name='password',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
