# Generated by Django 3.2.7 on 2021-12-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0017_auto_20211229_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default=9831034, max_length=16),
            preserve_default=False,
        ),
    ]
