# Generated by Django 3.2.7 on 2021-12-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TA_BOT_API', '0018_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
